export const GLOBAL_EVENTS = {
    CHANGE_ELEMENT_PROPS: 'change_element_props',
    GET_CHAT_MESSAGES: 'get_chat_messages',
    NEW_MESSAGE: 'new_message',
    SEND_MESSAGE: 'send_message',
    SEND_MESSAGE_CLICK: 'send_message_click',
    // FAVORITE: 'favorite_click',
    // PROFILE: 'profile_click',
    SEARCH: 'search_input',
    ADD_USER: 'add_user',
    // CHAT_ELEMENT: 'chat_click',
    // TO_REGISTRATION: 'to_registration',
    // FORGOT_PASS: 'forgot_pass',
    // PROFILE_RETURN: 'profile_return',
    // PROFILE_CHANGE: 'profile_change',
    SAVE_PROFILE: 'save_profile',
    // PASS_CHANGE: 'pass_change',
    // SAVE_PASS: 'save_pass',
    // UPLOAD_ATTACH: 'upload_attach',
    // SEND_MESSAGE: 'send_message',
    // PROFILE_DATA: 'profile_data',
    // PROFILE_SAVE_POSSIBILITY: 'profile_save_possibility',
    // PASS_SAVE_POSSIBILITY: 'pass_save_possibility',
};